### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by jackdelahunt** [redhat-developer/terraform-provider-rhoas#40]
It will be great to have some badges in the README file like [Go version](https://img.shields.io/github/go-mod/go-version/gomods/athens.svg), and [License](https://img.shields.io/badge/license-Apache--2.0-blue.svg).

**Comment by jonasniedermair** [comment]
@jackdelahunt  Hi, I can work on that :)

**Comment by jackdelahunt** [comment]
Hey @jonasniedermair sure go ahead 😄
