### ISSUE TITLE
Update contributing guidelines to document testing process

### ISSUE THREAD

**Issue by jackdelahunt** [redhat-developer/terraform-provider-rhoas#41]
Add a section to `CONTRIBUTING.md` describing how to run unit tests and our acceptance tests. Unit tests are ran by using the command `make test` in the root of the project and acceptance tests are ran by running `make testacc` in the root of the project

**Comment by lakshya8066** [comment]
Hey @jackdelahunt can I work on this?

**Comment by jackdelahunt** [comment]
Hey @lakshya8066 sure go ahead 😄
